"use client";

import type { CSSProperties } from "react";
import {
  ArrowLeft,
  Book,
  BookOpen,
  Brackets,
  Headphones,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CloudOff,
  CornerUpLeft,
  ExternalLink,
  Eye,
  EyeOff,
  FileClock,
  GitCompare,
  Layers,
  List,
  GripVertical,
  Info,
  Languages,
  Mic,
  Moon,
  Palette,
  Pause,
  Pencil,
  Play,
  Plus,
  Pointer,
  Repeat,
  RotateCcw,
  RotateCw,
  Search,
  Settings,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Flame,
  SkipBack,
  SkipForward,
  Sun,
  User,
  Users,
  Volume2,
  VolumeX,
  X,
  CreditCard,
  Sparkles,
  Smartphone,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "arrow-left": ArrowLeft,
  book: Book,
  "book-open": BookOpen,
  brackets: Brackets,
  headphones: Headphones,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "cloud-off": CloudOff,
  "corner-up-left": CornerUpLeft,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  "file-clock": FileClock,
  "git-compare": GitCompare,
  layers: Layers,
  list: List,
  "grip-vertical": GripVertical,
  info: Info,
  languages: Languages,
  mic: Mic,
  moon: Moon,
  palette: Palette,
  pause: Pause,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  pointer: Pointer,
  repeat: Repeat,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  search: Search,
  settings: Settings,
  "settings-2": Settings2,
  "shield-check": ShieldCheck,
  "sliders-horizontal": SlidersHorizontal,
  flame: Flame,
  "skip-back": SkipBack,
  "skip-forward": SkipForward,
  sun: Sun,
  user: User,
  users: Users,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  x: X,
  "credit-card": CreditCard,
  sparkles: Sparkles,
  smartphone: Smartphone,
};

export function Icon({
  name,
  size = 18,
  className,
  style,
}: {
  name: string;
  size?: number;
  className?: string;
  style?: CSSProperties;
}) {
  const Cmp = ICONS[name];
  if (!Cmp) return null;
  return <Cmp size={size} className={className} style={style} aria-hidden="true" strokeWidth={2} />;
}
